#!/bin/bash

SINK=$(pactl list short sinks | grep "RUNNING" | cut -f1)

if [[ -z $SINK ]]; then
	echo "";
fi

echo " $(pactl list sinks | grep "Sink #1" -A10 | tail -2 | grep -Eo "[0-9]{1,2}\%" | head -1)"
